### ISSUE TITLE
Add support for eID 2018 cards

### ISSUE THREAD

**Issue by Jyrno42** [thorgate/django-esteid#21]
This is an umbrella issue for the support of eID 2018 cards.

Issues that need to be resolved:

- [x] #10 Replace suds with zeep
- [x] #15 MobileID Signature verification
- [x] #12 Add support for ASiC-E (BDOC-TS) containers
- [x] Add new root certificates to `esteid/certs` directory
- [x] Update ISSUER_CERTS with new certificates [here](https://github.com/thorgate/django-esteid/blob/master/esteid/ocsp.py#L16)
- [x] Update signature verification code to support `ecdsa-with-SHA256`
- [x] Certificate serialNumber field has `PNOEE-` prefix

----

Misc things that might be of interest:

- No CRL in the certificate anymore, this might be a potential workaround for the [nginx issue](https://trac.nginx.org/nginx/ticket/1094)
- There is now a secondary OCSP service called [AIA-OCSP](http://aia.sk.ee/esteid2018)

Information about the new cards:

- https://www.id.ee/index.php?id=38674
- https://www.mkm.ee/sites/default/files/dhn_2018_09_19_eid.pdf
- https://installer.id.ee/media/id2019/TD-ID1-Chip-App.pdf

- [CRL Links](https://www.sk.ee/repositoorium/CRL/)
